services:
  postgres:
    container_name: postgres-sql-SchoolManagement
    image: postgres
    environment:
      POSTGRES_USER: sayari
      POSTGRES_PASSWORD: sayari
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB:  SchoolManagement
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped



volumes:
  postgres:

networks:
  spring-demo: